### ISSUE TITLE
Is it abandoned? Update signalr version.

### ISSUE THREAD

**Issue by seyfer** [dreamonkey/vue-signalr#1]
If not, update to signalR package version v7.

```
"@microsoft/signalr": "^7.0.4",
```

**Comment by IlCallo** [comment]
Hey there, the project isn't abandoned, but we're not working anymore on the project which required us to write and publish this package, so we'll update it as time permits and upon request

If you use this into a commercial project, please check out our sponsorship page to get issue prioritization: https://github.com/sponsors/dreamonkey/sponsorships?tier_id=135990

If you want to contribute by sending a PR and testing the changes on your project, that would help too :)

**Comment by IlCallo** [comment]
Btw, do you know where is it possible to check breaking changes across `@microsoft/signalr` major versions?
Which new feature do you need that older package versions don't support?

Unless it's needed due to breaking changes, I'd prefer to avoid a new major version of this package
If it's possible to support multiple major versions of `@microsoft/signalr` without breaking changes on our side, I'd go that route

**Comment by IlCallo** [comment]
From a quick look at the repo commits into the SignalR TS client, there doesn't seem to be any breaking changes which would affect this package, just internal or purely additional changes

Updating peerDependencies to accept newer versions of `@microsoft/signalr` [here](https://github.com/dreamonkey/vue-signalr/blob/9bd6c9f4032c3ab6405663438e53432aba3e41ee/package.json#LL30C5-L30C36) should be the way: `"@microsoft/signalr": "^5.0.0 || ^6.0.0 || ^7.0.0", as well as bumping [this](https://github.com/dreamonkey/vue-signalr/blob/9bd6c9f4032c3ab6405663438e53432aba3e41ee/package.json#LL35C5-L35C25)

**Comment by IlCallo** [comment]
I published a new version which bumps deps and accept new major version of signalr
Check out if it works for you
